--DROP DATABASE IF EXISTS Universiadi;

--CREATE DATABASE Universiadi;

--USE Universiadi;

/*per una creazione corretta delle tabelle, pulisco eventuale memoria*/

DROP TABLE IF EXISTS Nazione_Olimpiade;
DROP TABLE IF EXISTS Nazionalità;
DROP TABLE IF EXISTS Studia;
DROP TABLE IF EXISTS CorsoDiLaurea;
DROP TABLE IF EXISTS Università;
DROP TABLE IF EXISTS Partecipa;
DROP TABLE IF EXISTS Finanzia;
DROP TABLE IF EXISTS Competizione;
DROP TABLE IF EXISTS OlimpiadeUniversitaria;
DROP TABLE IF EXISTS Città;
DROP TABLE IF EXISTS FaParte;
DROP TABLE IF EXISTS Sponsorizza;
DROP TABLE IF EXISTS Squadra;
DROP TABLE IF EXISTS Nazione;
DROP TABLE IF EXISTS Disciplina;
DROP TABLE IF EXISTS Atleta;
DROP TABLE IF EXISTS Sponsor;

CREATE TABLE Sponsor (
	Nome VARCHAR(100) PRIMARY KEY,
	Telefono VARCHAR(15)
);

CREATE TABLE Atleta (
	Id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	Nome VARCHAR(50) NOT NULL,
	Cognome VARCHAR(50) NOT NULL,
	Sesso CHAR(1) NOT NULL
		CHECK (Sesso='M' OR Sesso='F'),
	DataNascita DATE NOT NULL
);

CREATE TABLE Disciplina (
	Nome VARCHAR(50),
	Sport VARCHAR(50),
	Regolamento TEXT NOT NULL,
	PRIMARY KEY (Nome, Sport)
);

CREATE TABLE Nazione (
	Nome VARCHAR(100) PRIMARY KEY
);

CREATE TABLE Squadra (
	Id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	Nazione VARCHAR(100) NOT NULL,
	FOREIGN KEY (Nazione) REFERENCES Nazione(Nome)
);

CREATE TABLE Sponsorizza (
	Sponsor VARCHAR(100),
	Squadra BIGINT,
	FOREIGN KEY (Sponsor) REFERENCES Sponsor(Nome),
	FOREIGN KEY (Squadra) REFERENCES Squadra(Id),
	PRIMARY KEY (Sponsor, Squadra)
);

CREATE TABLE FaParte (
	Squadra BIGINT,
	Atleta BIGINT,
	FOREIGN KEY (Squadra) REFERENCES Squadra(Id),
	FOREIGN KEY (Atleta) REFERENCES Atleta(Id),
	PRIMARY KEY (Squadra, Atleta)
);

CREATE TABLE Città (
	Id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	Nome VARCHAR(100) NOT NULL,
	Nazione VARCHAR(100) NOT NULL,
	FOREIGN KEY (Nazione) REFERENCES Nazione(Nome)
);

CREATE TABLE OlimpiadeUniversitaria (
	Anno SMALLINT PRIMARY KEY
		CHECK(Anno >= 1959),
	Città INT NOT NULL,
	FOREIGN KEY (Città) REFERENCES Città(Id)
);

CREATE TABLE Competizione (
	Sesso CHAR(1)
		CHECK (Sesso='M' OR Sesso='F' OR Sesso='E'), -- 'E' sta per entrambi
	Disciplina VARCHAR(50),
	Sport VARCHAR(50),
	Olimpiade SMALLINT,
	FOREIGN KEY (Disciplina, Sport) REFERENCES Disciplina(Nome, Sport),
	FOREIGN KEY (Olimpiade) REFERENCES OlimpiadeUniversitaria(Anno),
	PRIMARY KEY (Sesso, Disciplina, Sport, Olimpiade)
);

CREATE TABLE Finanzia (
	Sponsor VARCHAR(100),
	Sesso CHAR(1),
	Disciplina VARCHAR(50),
	Sport VARCHAR(50),
	Olimpiade SMALLINT,
	FOREIGN KEY (Sponsor) REFERENCES Sponsor(Nome),
	FOREIGN KEY (Sesso, Disciplina, Sport, Olimpiade) REFERENCES Competizione(Sesso, Disciplina, Sport, Olimpiade),
	PRIMARY KEY (Sponsor, Sesso, Disciplina, Sport, Olimpiade)
);

CREATE TABLE Partecipa (
	Squadra BIGINT,
	Sesso CHAR(1),
	Disciplina VARCHAR(50),
	Sport VARCHAR(50),
	Olimpiade SMALLINT,
	PosizioneClassifica SMALLINT,
	FOREIGN KEY (Squadra) REFERENCES Squadra(Id),
	FOREIGN KEY (Sesso, Disciplina, Sport, Olimpiade) REFERENCES Competizione(Sesso, Disciplina, Sport, Olimpiade),
	PRIMARY KEY (Squadra, Sesso, Disciplina, Sport, Olimpiade)
);

CREATE TABLE Università (
	Nome VARCHAR(100) PRIMARY KEY,
	Telefono VARCHAR(15),
	Città INT NOT NULL,
	Ori INT DEFAULT 0 NOT NULL,
	Argenti INT DEFAULT 0 NOT NULL,
	Bronzi INT DEFAULT 0 NOT NULL,
	FOREIGN KEY (Città) REFERENCES Città(Id)
);

CREATE TABLE CorsoDiLaurea (
	Nome VARCHAR(100),
	Università VARCHAR(100),
	FOREIGN KEY (Università) REFERENCES Università(Nome),
	PRIMARY KEY (Nome, Università)
);

CREATE TABLE Studia (
	Atleta BIGINT,
	NomeCorso VARCHAR(100),
	Università VARCHAR(100),
	AnnoAccademico SMALLINT NOT NULL -- anno in cui termina l'anno accademico
		CHECK (AnnoAccademico >= 1959),
	FOREIGN KEY (Atleta) REFERENCES Atleta(Id),
	FOREIGN KEY (NomeCorso, Università) REFERENCES CorsoDiLaurea(Nome, Università),
	PRIMARY KEY (Atleta, NomeCorso, Università)
);

CREATE TABLE Nazionalità (
	Atleta BIGINT,
	Nazione VARCHAR(100),
	FOREIGN KEY (Atleta) REFERENCES Atleta(Id),
	FOREIGN KEY (Nazione) REFERENCES Nazione(Nome),
	PRIMARY KEY (Atleta, Nazione)
);

CREATE TABLE Nazione_Olimpiade (
	Nazione VARCHAR(100),
	Olimpiade SMALLINT,
	Ori INT DEFAULT 0 NOT NULL,
	Argenti INT DEFAULT 0 NOT NULL,
	Bronzi INT DEFAULT 0 NOT NULL,
	FOREIGN KEY (Nazione) REFERENCES Nazione(Nome),
	FOREIGN KEY (Olimpiade) REFERENCES OlimpiadeUniversitaria(Anno),
	PRIMARY KEY (Nazione, Olimpiade)
);
